version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ../bnbexplorer-backend
    networks:
      - bnbexplorer
    ports:
      - "8080:8080"
    volumes:
      - ../bnbexplorer-backend/:/bnbexplorer-backend

  frontend:
    container_name: frontend
    build:
      context: ../bnbexplorer-frontend
    networks:
      - bnbexplorer
    ports:
      - "3000:3000"
    volumes:
      - ../bnbexplorer-frontend/:/bnbexplorer-frontend

networks:
  bnbexplorer: